apiVersion: v1
data:
  OIDC_CLIENT_SECRET: {{ .Values.ezua.oidc.client_secret | b64enc }} 
  OIDC_CLIENT_ID: {{ .Values.ezua.oidc.client_id | b64enc }} 
  OIDC_DOMAIN: {{ .Values.ezua.oidc.domain | b64enc }}
kind: Secret
metadata:
  name: {{ include "test-app.fullname" . }}-secrets
type: Opaque

